import colormaps.option_a
import colormaps.option_b
import colormaps.option_c
import colormaps.option_d
import colormaps.RdBuGnYl_r_v2
import colormaps.blu_grn_pnk2
import colormaps.parula
import colormaps.PuBuGnYl_r
import colormaps.RdBuGnYl_r
import colormaps.fake_parula
